---
- name: Run 'show vlan' on Cisco devices
  hosts: switches
  gather_facts: no
  tasks:
    - name: Execute show vlan command
      ios_command:
        commands: show vlan
        register: vlan_output
    - name: Display VLAN command output
      debug:
        var: vlan_output.stdout_lines